sudo: false

language: python

python:
    - 3.3
    - 3.4

install:
    - pip install neovim pyflakes nose

before_script:
    - git clone https://github.com/syngan/vim-vimlint /tmp/vim-vimlint
    - git clone https://github.com/ynkdir/vim-vimlparser /tmp/vim-vimlparser

script:
    - sh /tmp/vim-vimlint/bin/vimlint.sh -l /tmp/vim-vimlint -p /tmp/vim-vimlparser -e EVL103=1 -e EVL102.l:_=1 autoload
    - pyflakes rplugin/
    - nosetests rplugin/python3/
